# Github Actions
name: Github Actions

env:
  GLOBAL_ENV_VAR1: "environment variable 1 avaible for all jobs"
  GLOBAL_ENV_VAR2: "environment variable 2 avaible for all jobs"

on:
  push:
    branches: [ "main", "test/github-actions" ]
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
    - name: Execute one command
      run: echo "step 1"

    - name: Execute few commands
      run: |
        echo "command 1"
        echo "command 2"
        echo "command 3"

  job2:
    runs-on: ubuntu-latest
    env:
      JOB_ENV_VAR1: "environment variable 1 avaible for current job only"
      JOB_ENV_VAR2: "environment variable 2 avaible for current job only"

    steps:
    - name: Show Environment variables
      env:
        STEP_ENV_VAR1: "environment variable 1 avaible for current step only"
        STEP_ENV_VAR2: "environment variable 2 avaible for current step only"
      run: |
        echo "all jobs variables: ${{ env.GLOBAL_ENV_VAR1 }}, ${{ env.GLOBAL_ENV_VAR2 }}"
        echo "current job variables: ${{ env.JOB_ENV_VAR1 }}, ${{ env.JOB_ENV_VAR2 }}"
        echo "current step variables: ${{ env.STEP_ENV_VAR1 }}, ${{ env.STEP_ENV_VAR2 }}"
    
    - name: Show Github variables
      run: |
        echo "github.repository: ${{ github.repository }}"
        echo "github.actor: ${{ github.actor }}"
        echo "github.ref: ${{ github.ref }}"
        echo "github.sha: ${{ github.sha }}"
        echo "github.workflow: ${{ github.workflow }}"
        echo "github.event_name: ${{ github.event_name }}"
        echo "github.event_path: ${{ github.event_name }}"
        echo "github.job: ${{ github.job }}"
        echo "github.run_id: ${{ github.run_id }}"
        echo "github.run_number: ${{ github.run_number }}"

    - name: Show Runner variables
      run: |
        echo "runner.os: ${{ runner.os }}"
        echo "runner.arch: ${{ runner.arch }}"

    - name: Show Job variables
      run: |
        echo "job.status: ${{ job.status }}"

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]

    steps:
    - name: Check component versions
      run: |
        docker --version
        aws --version
        zip --version

  job4:
    runs-on: ubuntu-latest

    steps:
    - name: List current directory
      run: ls -la

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: List current directory
      run: ls -la

  job5:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        var1: [11, 12]
        var2: [1, 2, 3]
        include:
          - var3: 0
          - var1: 11
            var2: 2
            flags: "flag"
          - var1: 21
            var2: 1
        exclude:
          - var1: 12
            var2: 3

    steps:
      - name: Show Matrix values
        run: |
          echo "var1: ${{ matrix.var1 }}"
          echo "var2: ${{ matrix.var2 }}"
          echo "var3: ${{ matrix.var3 }}"
          echo "flags: ${{ matrix.flags || 'no flags' }}"

  job6:
    runs-on: ubuntu-latest

    steps:
      - name: Print to Summary
        run: echo "Job6" >> $GITHUB_STEP_SUMMARY

      - name: Expressions
        env:
          abc: "abc"
        run: |
          echo "startsWith(env.abc, 'a') || endsWith(env.abc, 'c'): "
          echo -n "${{ startsWith(env.abc, 'a') || endsWith(env.abc, 'c') }}"
          echo "contains(env.abc, 'bc'): "
          echo -n "${{ contains(env.abc, 'bc') }}"

      - name: Github Context
        run: |
          echo "${{ toJson(github.event_name) }}"
          echo "${{ toJson(github.event) }}"
